//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Views.Account {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Login {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        internal Login() {
        }

        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    resourceMan = new System.Resources.ResourceManager("App.Resources.Views.Account.Login", typeof(Login).Assembly);
                }
                return resourceMan;
            }
        }

        public static System.Globalization.CultureInfo Culture {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string Title => ResourceManager.GetString("Title", resourceCulture);
        public static string Email => ResourceManager.GetString("Email", resourceCulture);
        public static string Password => ResourceManager.GetString("Password", resourceCulture);
        public static string RememberMe => ResourceManager.GetString("RememberMe", resourceCulture);
        public static string Submit => ResourceManager.GetString("Submit", resourceCulture);
        public static string NoAccountYet => ResourceManager.GetString("NoAccountYet", resourceCulture);
        public static string RegisterLinkText => ResourceManager.GetString("RegisterLinkText", resourceCulture);
    }
}

