//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Views.Account {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Register {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        internal Register() {
        }

        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    resourceMan = new System.Resources.ResourceManager("App.Resources.Views.Account.Register", typeof(Register).Assembly);
                }
                return resourceMan;
            }
        }

        public static System.Globalization.CultureInfo Culture {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string Title => ResourceManager.GetString("Title", resourceCulture);
        public static string NeedCompanyAccount => ResourceManager.GetString("NeedCompanyAccount", resourceCulture);
        public static string RegisterCompany => ResourceManager.GetString("RegisterCompany", resourceCulture);
        public static string FirstName => ResourceManager.GetString("FirstName", resourceCulture);
        public static string LastName => ResourceManager.GetString("LastName", resourceCulture);
        public static string Email => ResourceManager.GetString("Email", resourceCulture);
        public static string Phone => ResourceManager.GetString("Phone", resourceCulture);
        public static string Password => ResourceManager.GetString("Password", resourceCulture);
        public static string ConfirmPassword => ResourceManager.GetString("ConfirmPassword", resourceCulture);
        public static string Submit => ResourceManager.GetString("Submit", resourceCulture);
    }
}

