// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace App.Resources.Views.Company.Dashboard {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StationStatus {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        internal StationStatus() {
        }

        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    var temp = new System.Resources.ResourceManager("App.Resources.Views.Company.Dashboard.StationStatus", typeof(StationStatus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        public static System.Globalization.CultureInfo Culture {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string Title => ResourceManager.GetString("Title", resourceCulture);
        public static string Heading => ResourceManager.GetString("Heading", resourceCulture);
        public static string BackToDashboard => ResourceManager.GetString("BackToDashboard", resourceCulture);
        public static string NoStations => ResourceManager.GetString("NoStations", resourceCulture);
        public static string StationColumn => ResourceManager.GetString("StationColumn", resourceCulture);
        public static string HealthColumn => ResourceManager.GetString("HealthColumn", resourceCulture);
        public static string UtilizationColumn => ResourceManager.GetString("UtilizationColumn", resourceCulture);
        public static string ActiveSessionsColumn => ResourceManager.GetString("ActiveSessionsColumn", resourceCulture);
        public static string ReservationsColumn => ResourceManager.GetString("ReservationsColumn", resourceCulture);
        public static string PendingMaintenanceColumn => ResourceManager.GetString("PendingMaintenanceColumn", resourceCulture);
        public static string ActionsColumn => ResourceManager.GetString("ActionsColumn", resourceCulture);
        public static string DetailsAction => ResourceManager.GetString("DetailsAction", resourceCulture);
    }
}
