// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace App.Resources.Views.Company.Audit {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CompanyLog {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        internal CompanyLog() {
        }

        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    var temp = new System.Resources.ResourceManager("WebAppClient.App.Resources.Views.Company.Audit.CompanyLog", typeof(CompanyLog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        public static System.Globalization.CultureInfo Culture {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string Title => ResourceManager.GetString("Title", resourceCulture);
        public static string Heading => ResourceManager.GetString("Heading", resourceCulture);
        public static string FromUtc => ResourceManager.GetString("FromUtc", resourceCulture);
        public static string ToUtc => ResourceManager.GetString("ToUtc", resourceCulture);
        public static string EntityName => ResourceManager.GetString("EntityName", resourceCulture);
        public static string Action => ResourceManager.GetString("Action", resourceCulture);
        public static string ApplyFilters => ResourceManager.GetString("ApplyFilters", resourceCulture);
        public static string NoEntries => ResourceManager.GetString("NoEntries", resourceCulture);
        public static string Actor => ResourceManager.GetString("Actor", resourceCulture);
        public static string AtUtc => ResourceManager.GetString("AtUtc", resourceCulture);
        public static string Changes => ResourceManager.GetString("Changes", resourceCulture);
    }
}

