stages:
  - deploy

deploy:
  stage: deploy
  only:
    - main
  tags:
    - shared
  script:
    - docker --version
    - docker compose version
    - test -f project/docker-compose.yml
    - test -f project/Dockerfile
    - test -f WebAppClient/docker-compose.yml
    - test -f WebAppClient/Dockerfile
    - docker compose -f project/docker-compose.yml -f WebAppClient/docker-compose.yml -p kunnap-modular-monolith config
    - docker compose -f project/docker-compose.yml -f WebAppClient/docker-compose.yml -p kunnap-modular-monolith pull chargepanel-modular-monolith-postgres
    - docker compose -f project/docker-compose.yml -f WebAppClient/docker-compose.yml -p kunnap-modular-monolith up --build --remove-orphans --detach || (docker compose -f project/docker-compose.yml -f WebAppClient/docker-compose.yml -p kunnap-modular-monolith logs --tail=200 chargepanel-modular-monolith-postgres chargepanel-modular-monolith-webapp webappclient && false)
