// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace App.Resources.Views.Root.ChargingSession {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Details {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        internal Details() {
        }

        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    var temp = new System.Resources.ResourceManager("App.Resources.Views.Root.ChargingSession.Details", typeof(Details).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        public static System.Globalization.CultureInfo Culture {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string Title => ResourceManager.GetString("Title", resourceCulture);
        public static string Heading => ResourceManager.GetString("Heading", resourceCulture);
        public static string StartTime => ResourceManager.GetString("StartTime", resourceCulture);
        public static string EndTime => ResourceManager.GetString("EndTime", resourceCulture);
        public static string DurationMinutes => ResourceManager.GetString("DurationMinutes", resourceCulture);
        public static string EnergyConsumed => ResourceManager.GetString("EnergyConsumed", resourceCulture);
        public static string StatusActive => ResourceManager.GetString("StatusActive", resourceCulture);
        public static string StatusCompleted => ResourceManager.GetString("StatusCompleted", resourceCulture);
        public static string FinalCost => ResourceManager.GetString("FinalCost", resourceCulture);
        public static string BackToHistory => ResourceManager.GetString("BackToHistory", resourceCulture);
        public static string EnergyInputPlaceholder => ResourceManager.GetString("EnergyInputPlaceholder", resourceCulture);
        public static string DurationInputPlaceholder => ResourceManager.GetString("DurationInputPlaceholder", resourceCulture);
        public static string StopSession => ResourceManager.GetString("StopSession", resourceCulture);
    }
}

