// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace App.Resources.Views.Root.ChargingSession {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class History {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        internal History() {
        }

        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    var temp = new System.Resources.ResourceManager("App.Resources.Views.Root.ChargingSession.History", typeof(History).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        public static System.Globalization.CultureInfo Culture {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string Title => ResourceManager.GetString("Title", resourceCulture);
        public static string Heading => ResourceManager.GetString("Heading", resourceCulture);
        public static string NoSessions => ResourceManager.GetString("NoSessions", resourceCulture);
        public static string StatusActive => ResourceManager.GetString("StatusActive", resourceCulture);
        public static string StatusCompleted => ResourceManager.GetString("StatusCompleted", resourceCulture);
        public static string EnergyLabel => ResourceManager.GetString("EnergyLabel", resourceCulture);
        public static string CostLabel => ResourceManager.GetString("CostLabel", resourceCulture);
        public static string Details => ResourceManager.GetString("Details", resourceCulture);
    }
}

