// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace App.Resources.Views.Root.ChargingSession {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Start {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        internal Start() {
        }

        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    var temp = new System.Resources.ResourceManager("App.Resources.Views.Root.ChargingSession.Start", typeof(Start).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        public static System.Globalization.CultureInfo Culture {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string Title => ResourceManager.GetString("Title", resourceCulture);
        public static string Heading => ResourceManager.GetString("Heading", resourceCulture);
        public static string EstimatedDuration => ResourceManager.GetString("EstimatedDuration", resourceCulture);
        public static string Minutes => ResourceManager.GetString("Minutes", resourceCulture);
        public static string EstimatedCost => ResourceManager.GetString("EstimatedCost", resourceCulture);
        public static string Confirm => ResourceManager.GetString("Confirm", resourceCulture);
        public static string BackToReservations => ResourceManager.GetString("BackToReservations", resourceCulture);
    }
}

