// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace App.Resources.Views.Admin.AuditLogs {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        internal Index() {
        }

        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    var temp = new System.Resources.ResourceManager("App.Resources.Views.Admin.AuditLogs.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        public static System.Globalization.CultureInfo Culture {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string Title => ResourceManager.GetString("Title", resourceCulture);
        public static string Heading => ResourceManager.GetString("Heading", resourceCulture);
        public static string FromUtc => ResourceManager.GetString("FromUtc", resourceCulture);
        public static string ToUtc => ResourceManager.GetString("ToUtc", resourceCulture);
        public static string EntityName => ResourceManager.GetString("EntityName", resourceCulture);
        public static string Action => ResourceManager.GetString("Action", resourceCulture);
        public static string Actor => ResourceManager.GetString("Actor", resourceCulture);
        public static string EntityId => ResourceManager.GetString("EntityId", resourceCulture);
        public static string ApplyFilters => ResourceManager.GetString("ApplyFilters", resourceCulture);
        public static string DashboardAction => ResourceManager.GetString("DashboardAction", resourceCulture);
        public static string CompaniesAction => ResourceManager.GetString("CompaniesAction", resourceCulture);
        public static string NoEntries => ResourceManager.GetString("NoEntries", resourceCulture);
        public static string TableHeading => ResourceManager.GetString("TableHeading", resourceCulture);
        public static string AtUtc => ResourceManager.GetString("AtUtc", resourceCulture);
        public static string Company => ResourceManager.GetString("Company", resourceCulture);
        public static string Changes => ResourceManager.GetString("Changes", resourceCulture);
        public static string PreviousPage => ResourceManager.GetString("PreviousPage", resourceCulture);
        public static string NextPage => ResourceManager.GetString("NextPage", resourceCulture);
        public static string PageSummary => ResourceManager.GetString("PageSummary", resourceCulture);
        public static string InvalidEntityId => ResourceManager.GetString("InvalidEntityId", resourceCulture);
    }
}
