// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace App.Resources.Views.Admin.Promotions {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        internal Index() {
        }

        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    var temp = new System.Resources.ResourceManager("App.Resources.Views.Admin.Promotions.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        public static System.Globalization.CultureInfo Culture {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string ActionsHeader => ResourceManager.GetString("ActionsHeader", resourceCulture);
        public static string ActiveStatus => ResourceManager.GetString("ActiveStatus", resourceCulture);
        public static string CodeHeader => ResourceManager.GetString("CodeHeader", resourceCulture);
        public static string CreateButtonLabel => ResourceManager.GetString("CreateButtonLabel", resourceCulture);
        public static string DeleteConfirm => ResourceManager.GetString("DeleteConfirm", resourceCulture);
        public static string DiscountHeader => ResourceManager.GetString("DiscountHeader", resourceCulture);
        public static string InactiveStatus => ResourceManager.GetString("InactiveStatus", resourceCulture);
        public static string NoPromos => ResourceManager.GetString("NoPromos", resourceCulture);
        public static string StatusHeader => ResourceManager.GetString("StatusHeader", resourceCulture);
        public static string Title => ResourceManager.GetString("Title", resourceCulture);
        public static string ValidFromHeader => ResourceManager.GetString("ValidFromHeader", resourceCulture);
        public static string ValidToHeader => ResourceManager.GetString("ValidToHeader", resourceCulture);
    }
}
