// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace App.Resources.Views.Admin.Audit {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Trail {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        internal Trail() {
        }

        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    var temp = new System.Resources.ResourceManager("WebAppClient.App.Resources.Views.Admin.Audit.Trail", typeof(Trail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        public static System.Globalization.CultureInfo Culture {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string Title => ResourceManager.GetString("Title", resourceCulture);
        public static string Heading => ResourceManager.GetString("Heading", resourceCulture);
        public static string EntityId => ResourceManager.GetString("EntityId", resourceCulture);
        public static string NoEntries => ResourceManager.GetString("NoEntries", resourceCulture);
        public static string Actor => ResourceManager.GetString("Actor", resourceCulture);
        public static string AtUtc => ResourceManager.GetString("AtUtc", resourceCulture);
        public static string Changes => ResourceManager.GetString("Changes", resourceCulture);
    }
}

