//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Views.Shared {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Layout {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Layout() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("App.Resources.Views.Shared._Layout", typeof(_Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        public static string AdminCompanies {
            get {
                return ResourceManager.GetString("AdminCompanies", resourceCulture);
            }
        }
        
        public static string AdminAppUserCompanies {
            get {
                return ResourceManager.GetString("AdminAppUserCompanies", resourceCulture);
            }
        }
        
        public static string AdminChargingStations {
            get {
                return ResourceManager.GetString("AdminChargingStations", resourceCulture);
            }
        }
        
        public static string AdminStationConnectors {
            get {
                return ResourceManager.GetString("AdminStationConnectors", resourceCulture);
            }
        }
        
        public static string AdminChargingSessions {
            get {
                return ResourceManager.GetString("AdminChargingSessions", resourceCulture);
            }
        }
        
        public static string AdminConnectors {
            get {
                return ResourceManager.GetString("AdminConnectors", resourceCulture);
            }
        }
        
        public static string AdminVehicles {
            get {
                return ResourceManager.GetString("AdminVehicles", resourceCulture);
            }
        }
        
        public static string AdminVehicleConnectors {
            get {
                return ResourceManager.GetString("AdminVehicleConnectors", resourceCulture);
            }
        }
        
        public static string AdminReservations {
            get {
                return ResourceManager.GetString("AdminReservations", resourceCulture);
            }
        }
        
        public static string AdminPromotions {
            get {
                return ResourceManager.GetString("AdminPromotions", resourceCulture);
            }
        }
        
        public static string AdminUserPromotions {
            get {
                return ResourceManager.GetString("AdminUserPromotions", resourceCulture);
            }
        }
        
        public static string AdminMaintenances {
            get {
                return ResourceManager.GetString("AdminMaintenances", resourceCulture);
            }
        }
        
        public static string AdminAuditLogs {
            get {
                return ResourceManager.GetString("AdminAuditLogs", resourceCulture);
            }
        }

        public static string FindStations {
            get {
                return ResourceManager.GetString("FindStations", resourceCulture);
            }
        }

        public static string MyReservations {
            get {
                return ResourceManager.GetString("MyReservations", resourceCulture);
            }
        }

        public static string MySessions {
            get {
                return ResourceManager.GetString("MySessions", resourceCulture);
            }
        }

        public static string MyVehicles {
            get {
                return ResourceManager.GetString("MyVehicles", resourceCulture);
            }
        }

        public static string MyPromotions {
            get {
                return ResourceManager.GetString("MyPromotions", resourceCulture);
            }
        }

        public static string CompanyAudit {
            get {
                return ResourceManager.GetString("CompanyAudit", resourceCulture);
            }
        }

        public static string CompanyDashboard {
            get {
                return ResourceManager.GetString("CompanyDashboard", resourceCulture);
            }
        }

        public static string CompanyStations {
            get {
                return ResourceManager.GetString("CompanyStations", resourceCulture);
            }
        }

        public static string CompanyMaintenance {
            get {
                return ResourceManager.GetString("CompanyMaintenance", resourceCulture);
            }
        }

        public static string CompanyPromotions {
            get {
                return ResourceManager.GetString("CompanyPromotions", resourceCulture);
            }
        }

        public static string PaymentMethods {
            get {
                return ResourceManager.GetString("PaymentMethods", resourceCulture);
            }
        }

        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
    }
}
