// <auto-generated>
//     This code was generated by a tool.
// <auto-generated>
//     This code was generated by a tool.
//
//------------------------------------------------------------------------------



namespace App.Resources.Views.Root.Reservation {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        internal Index() {
        }

        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    var temp = new System.Resources.ResourceManager("App.Resources.Views.Root.Reservation.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        public static System.Globalization.CultureInfo Culture {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string Title => ResourceManager.GetString("Title", resourceCulture);
        public static string Heading => ResourceManager.GetString("Heading", resourceCulture);
        public static string NoReservations => ResourceManager.GetString("NoReservations", resourceCulture);
        public static string Details => ResourceManager.GetString("Details", resourceCulture);
        public static string Cancel => ResourceManager.GetString("Cancel", resourceCulture);
        public static string Start => ResourceManager.GetString("Start", resourceCulture);
        public static string StatusActive => ResourceManager.GetString("StatusActive", resourceCulture);
        public static string StatusStarted => ResourceManager.GetString("StatusStarted", resourceCulture);
    }
}
// </auto-generated>
//------------------------------------------------------------------------------
