// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace App.Resources.Views.Company.Maintenance {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Details {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        internal Details() {
        }

        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    var temp = new System.Resources.ResourceManager("App.Resources.Views.Company.Maintenance.Details", typeof(Details).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        public static System.Globalization.CultureInfo Culture {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string Title => ResourceManager.GetString("Title", resourceCulture);
        public static string Heading => ResourceManager.GetString("Heading", resourceCulture);
        public static string ViewStation => ResourceManager.GetString("ViewStation", resourceCulture);
        public static string BackToList => ResourceManager.GetString("BackToList", resourceCulture);
        public static string Status => ResourceManager.GetString("Status", resourceCulture);
        public static string ReportedAt => ResourceManager.GetString("ReportedAt", resourceCulture);
        public static string ResolvedAt => ResourceManager.GetString("ResolvedAt", resourceCulture);
        public static string NotResolved => ResourceManager.GetString("NotResolved", resourceCulture);
        public static string AssignedTo => ResourceManager.GetString("AssignedTo", resourceCulture);
        public static string Unassigned => ResourceManager.GetString("Unassigned", resourceCulture);
        public static string Reporter => ResourceManager.GetString("Reporter", resourceCulture);
        public static string Unknown => ResourceManager.GetString("Unknown", resourceCulture);
        public static string Notes => ResourceManager.GetString("Notes", resourceCulture);
        public static string UpdateStatusHeading => ResourceManager.GetString("UpdateStatusHeading", resourceCulture);
        public static string NotesPlaceholder => ResourceManager.GetString("NotesPlaceholder", resourceCulture);
        public static string UpdateAction => ResourceManager.GetString("UpdateAction", resourceCulture);
        public static string AssignmentHeading => ResourceManager.GetString("AssignmentHeading", resourceCulture);
        public static string AssignToMe => ResourceManager.GetString("AssignToMe", resourceCulture);
        public static string ClearAssignment => ResourceManager.GetString("ClearAssignment", resourceCulture);
        public static string HistoryHeading => ResourceManager.GetString("HistoryHeading", resourceCulture);
        public static string NoHistory => ResourceManager.GetString("NoHistory", resourceCulture);
        public static string HistoryAt => ResourceManager.GetString("HistoryAt", resourceCulture);
        public static string HistoryAction => ResourceManager.GetString("HistoryAction", resourceCulture);
        public static string HistoryActor => ResourceManager.GetString("HistoryActor", resourceCulture);
        public static string HistoryChanges => ResourceManager.GetString("HistoryChanges", resourceCulture);
    }
}
