//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Views.Home {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    var temp = new System.Resources.ResourceManager("App.Resources.Views.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Title => ResourceManager.GetString("Title", resourceCulture);
        public static string SearchLocationPlaceholder => ResourceManager.GetString("SearchLocationPlaceholder", resourceCulture);
        public static string Filters => ResourceManager.GetString("Filters", resourceCulture);
        public static string AvailableNow => ResourceManager.GetString("AvailableNow", resourceCulture);
        public static string FastCharging => ResourceManager.GetString("FastCharging", resourceCulture);
        public static string CompatibleWithMyVehicle => ResourceManager.GetString("CompatibleWithMyVehicle", resourceCulture);
        public static string SelectVehicle => ResourceManager.GetString("SelectVehicle", resourceCulture);
        public static string NearbyStations => ResourceManager.GetString("NearbyStations", resourceCulture);
        public static string NoStationsFoundYet => ResourceManager.GetString("NoStationsFoundYet", resourceCulture);
        public static string StatusAvailable => ResourceManager.GetString("StatusAvailable", resourceCulture);
        public static string StatusLimitedAvailability => ResourceManager.GetString("StatusLimitedAvailability", resourceCulture);
        public static string StatusInUse => ResourceManager.GetString("StatusInUse", resourceCulture);
        public static string StatusUnavailable => ResourceManager.GetString("StatusUnavailable", resourceCulture);
        public static string Supported => ResourceManager.GetString("Supported", resourceCulture);
        public static string Hour => ResourceManager.GetString("Hour", resourceCulture);
        public static string MaxPower => ResourceManager.GetString("MaxPower", resourceCulture);
        public static string Details => ResourceManager.GetString("Details", resourceCulture);
    }
}

