//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Views.Home {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("App.Resources.Views.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        public static string SearchLocationPlaceholder {
            get {
                return ResourceManager.GetString("SearchLocationPlaceholder", resourceCulture);
            }
        }
        
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        public static string AvailableNow {
            get {
                return ResourceManager.GetString("AvailableNow", resourceCulture);
            }
        }
        
        public static string ClearFilters {
            get {
                return ResourceManager.GetString("ClearFilters", resourceCulture);
            }
        }
        
        public static string CompatibleWithMyVehicle {
            get {
                return ResourceManager.GetString("CompatibleWithMyVehicle", resourceCulture);
            }
        }
        
        public static string SelectVehicle {
            get {
                return ResourceManager.GetString("SelectVehicle", resourceCulture);
            }
        }
        
        public static string NearbyStations {
            get {
                return ResourceManager.GetString("NearbyStations", resourceCulture);
            }
        }
        
        public static string NoStationsFoundYet {
            get {
                return ResourceManager.GetString("NoStationsFoundYet", resourceCulture);
            }
        }
        
        public static string StatusAvailable {
            get {
                return ResourceManager.GetString("StatusAvailable", resourceCulture);
            }
        }
        
        public static string StatusLimitedAvailability {
            get {
                return ResourceManager.GetString("StatusLimitedAvailability", resourceCulture);
            }
        }
        
        public static string StatusInUse {
            get {
                return ResourceManager.GetString("StatusInUse", resourceCulture);
            }
        }
        
        public static string StatusUnavailable {
            get {
                return ResourceManager.GetString("StatusUnavailable", resourceCulture);
            }
        }
        
        public static string Supported {
            get {
                return ResourceManager.GetString("Supported", resourceCulture);
            }
        }
        
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        public static string MaxPower {
            get {
                return ResourceManager.GetString("MaxPower", resourceCulture);
            }
        }
        
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }

        public static string AllVehicles {
            get {
                return ResourceManager.GetString("AllVehicles", resourceCulture);
            }
        }

        public static string Compatible {
            get {
                return ResourceManager.GetString("Compatible", resourceCulture);
            }
        }

        public static string Incompatible {
            get {
                return ResourceManager.GetString("Incompatible", resourceCulture);
            }
        }
    }
}
