// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace App.Resources.Views.Admin.Companies {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        internal Index() {
        }

        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    var temp = new System.Resources.ResourceManager("App.Resources.Views.Admin.Companies.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        public static System.Globalization.CultureInfo Culture {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string Title => ResourceManager.GetString("Title", resourceCulture);
        public static string Heading => ResourceManager.GetString("Heading", resourceCulture);
        public static string Search => ResourceManager.GetString("Search", resourceCulture);
        public static string SearchPlaceholder => ResourceManager.GetString("SearchPlaceholder", resourceCulture);
        public static string ApplySearch => ResourceManager.GetString("ApplySearch", resourceCulture);
        public static string DashboardAction => ResourceManager.GetString("DashboardAction", resourceCulture);
        public static string AuditAction => ResourceManager.GetString("AuditAction", resourceCulture);
        public static string NoCompanies => ResourceManager.GetString("NoCompanies", resourceCulture);
        public static string TableHeading => ResourceManager.GetString("TableHeading", resourceCulture);
        public static string Company => ResourceManager.GetString("Company", resourceCulture);
        public static string Slug => ResourceManager.GetString("Slug", resourceCulture);
        public static string Members => ResourceManager.GetString("Members", resourceCulture);
        public static string Status => ResourceManager.GetString("Status", resourceCulture);
        public static string Actions => ResourceManager.GetString("Actions", resourceCulture);
        public static string Active => ResourceManager.GetString("Active", resourceCulture);
        public static string Inactive => ResourceManager.GetString("Inactive", resourceCulture);
        public static string Activate => ResourceManager.GetString("Activate", resourceCulture);
        public static string Inactivate => ResourceManager.GetString("Inactivate", resourceCulture);
        public static string CompanyActivated => ResourceManager.GetString("CompanyActivated", resourceCulture);
        public static string CompanyInactivated => ResourceManager.GetString("CompanyInactivated", resourceCulture);
    }
}
