// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace App.Resources.Views.Admin.ConnectorTypes {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        internal Index() {
        }

        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    var temp = new System.Resources.ResourceManager("App.Resources.Views.Admin.ConnectorTypes.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        public static System.Globalization.CultureInfo Culture {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string Title => ResourceManager.GetString("Title", resourceCulture);
        public static string Heading => ResourceManager.GetString("Heading", resourceCulture);
        public static string Search => ResourceManager.GetString("Search", resourceCulture);
        public static string SearchPlaceholder => ResourceManager.GetString("SearchPlaceholder", resourceCulture);
        public static string ApplySearch => ResourceManager.GetString("ApplySearch", resourceCulture);
        public static string AddConnectorType => ResourceManager.GetString("AddConnectorType", resourceCulture);
        public static string DashboardAction => ResourceManager.GetString("DashboardAction", resourceCulture);
        public static string NoConnectorTypes => ResourceManager.GetString("NoConnectorTypes", resourceCulture);
        public static string TableHeading => ResourceManager.GetString("TableHeading", resourceCulture);
        public static string Name => ResourceManager.GetString("Name", resourceCulture);
        public static string Status => ResourceManager.GetString("Status", resourceCulture);
        public static string Actions => ResourceManager.GetString("Actions", resourceCulture);
        public static string Active => ResourceManager.GetString("Active", resourceCulture);
        public static string Inactive => ResourceManager.GetString("Inactive", resourceCulture);
        public static string Edit => ResourceManager.GetString("Edit", resourceCulture);
        public static string Delete => ResourceManager.GetString("Delete", resourceCulture);
        public static string CreateTitle => ResourceManager.GetString("CreateTitle", resourceCulture);
        public static string EditTitle => ResourceManager.GetString("EditTitle", resourceCulture);
        public static string NameEn => ResourceManager.GetString("NameEn", resourceCulture);
        public static string NameEt => ResourceManager.GetString("NameEt", resourceCulture);
        public static string IsActiveLabel => ResourceManager.GetString("IsActiveLabel", resourceCulture);
        public static string CreateAction => ResourceManager.GetString("CreateAction", resourceCulture);
        public static string SaveChanges => ResourceManager.GetString("SaveChanges", resourceCulture);
        public static string BackToList => ResourceManager.GetString("BackToList", resourceCulture);
        public static string ConnectorTypeCreated => ResourceManager.GetString("ConnectorTypeCreated", resourceCulture);
        public static string ConnectorTypeUpdated => ResourceManager.GetString("ConnectorTypeUpdated", resourceCulture);
        public static string ConnectorTypeDeleted => ResourceManager.GetString("ConnectorTypeDeleted", resourceCulture);
    }
}
