<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Update="Views\Shared\_Layout.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>_Layout.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Views\Home\Index.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Index.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Views\Account\Login.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Login.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Views\Account\Register.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Register.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Views\Account\AccessDenied.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>AccessDenied.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Views\Account\LoggedOut.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>LoggedOut.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Views\Account\CompanySelection.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>CompanySelection.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Views\Root\Vehicle\Index.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Index.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Views\Root\Vehicle\Create.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Create.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Views\Root\Vehicle\Edit.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Edit.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Views\Root\Station\Details.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Details.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Views\Root\Reservation\Index.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Index.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Views\Root\Reservation\Create.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Create.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Views\Root\Reservation\Details.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Details.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\Shared\_Layout.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>_Layout.resx</DependentUpon>
      </Compile>
      <Compile Update="Views\Home\Index.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Index.resx</DependentUpon>
      </Compile>
      <Compile Update="Views\Account\Login.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Login.resx</DependentUpon>
      </Compile>
      <Compile Update="Views\Account\Register.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Register.resx</DependentUpon>
      </Compile>
      <Compile Update="Views\Account\AccessDenied.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>AccessDenied.resx</DependentUpon>
      </Compile>
      <Compile Update="Views\Account\LoggedOut.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>LoggedOut.resx</DependentUpon>
      </Compile>
      <Compile Update="Views\Account\CompanySelection.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>CompanySelection.resx</DependentUpon>
      </Compile>
      <Compile Update="Views\Root\Vehicle\Index.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Index.resx</DependentUpon>
      </Compile>
      <Compile Update="Views\Root\Vehicle\Create.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Create.resx</DependentUpon>
      </Compile>
      <Compile Update="Views\Root\Vehicle\Edit.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Edit.resx</DependentUpon>
      </Compile>
      <Compile Update="Views\Root\Station\Details.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Details.resx</DependentUpon>
      </Compile>
      <Compile Update="Views\Root\Reservation\Index.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Index.resx</DependentUpon>
      </Compile>
      <Compile Update="Views\Root\Reservation\Create.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Create.resx</DependentUpon>
      </Compile>
      <Compile Update="Views\Root\Reservation\Details.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Details.resx</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
