// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace App.Resources.Views.Company.Station {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Details {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        internal Details() {
        }

        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    var temp = new System.Resources.ResourceManager("WebAppClient.App.Resources.Views.Company.Station.Details", typeof(Details).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        public static System.Globalization.CultureInfo Culture {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string Title => ResourceManager.GetString("Title", resourceCulture);
        public static string Heading => ResourceManager.GetString("Heading", resourceCulture);
        public static string ReportIssue => ResourceManager.GetString("ReportIssue", resourceCulture);
        public static string BackToStations => ResourceManager.GetString("BackToStations", resourceCulture);
        public static string EditAction => ResourceManager.GetString("EditAction", resourceCulture);
        public static string MaxPower => ResourceManager.GetString("MaxPower", resourceCulture);
        public static string Connectors => ResourceManager.GetString("Connectors", resourceCulture);
        public static string ActiveMaintenance => ResourceManager.GetString("ActiveMaintenance", resourceCulture);
        public static string RecentMaintenanceHeading => ResourceManager.GetString("RecentMaintenanceHeading", resourceCulture);
        public static string NoMaintenance => ResourceManager.GetString("NoMaintenance", resourceCulture);
    }
}
