// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace App.Resources.Views.Company.Station {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Edit {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        internal Edit() {
        }

        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    var temp = new System.Resources.ResourceManager("WebAppClient.App.Resources.Views.Company.Station.Edit", typeof(Edit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        public static System.Globalization.CultureInfo Culture {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string Title => ResourceManager.GetString("Title", resourceCulture);
        public static string Heading => ResourceManager.GetString("Heading", resourceCulture);
        public static string NameEnLabel => ResourceManager.GetString("NameEnLabel", resourceCulture);
        public static string NameEtLabel => ResourceManager.GetString("NameEtLabel", resourceCulture);
        public static string NameEnPlaceholder => ResourceManager.GetString("NameEnPlaceholder", resourceCulture);
        public static string NameEtPlaceholder => ResourceManager.GetString("NameEtPlaceholder", resourceCulture);
        public static string LocationLabel => ResourceManager.GetString("LocationLabel", resourceCulture);
        public static string PriceLabel => ResourceManager.GetString("PriceLabel", resourceCulture);
        public static string MaxPowerLabel => ResourceManager.GetString("MaxPowerLabel", resourceCulture);
        public static string StatusLabel => ResourceManager.GetString("StatusLabel", resourceCulture);
        public static string ConnectorsLabel => ResourceManager.GetString("ConnectorsLabel", resourceCulture);
        public static string IsActiveLabel => ResourceManager.GetString("IsActiveLabel", resourceCulture);
        public static string SaveAction => ResourceManager.GetString("SaveAction", resourceCulture);
        public static string BackAction => ResourceManager.GetString("BackAction", resourceCulture);
        public static string DetailsAction => ResourceManager.GetString("DetailsAction", resourceCulture);
        public static string ConnectorManagementHeading => ResourceManager.GetString("ConnectorManagementHeading", resourceCulture);
        public static string AssignConnectorAction => ResourceManager.GetString("AssignConnectorAction", resourceCulture);
        public static string RemoveConnectorAction => ResourceManager.GetString("RemoveConnectorAction", resourceCulture);
    }
}
