// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace App.Resources.Views.Company.Station {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        internal Index() {
        }

        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    var temp = new System.Resources.ResourceManager("WebAppClient.App.Resources.Views.Company.Station.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        public static System.Globalization.CultureInfo Culture {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string Title => ResourceManager.GetString("Title", resourceCulture);
        public static string Heading => ResourceManager.GetString("Heading", resourceCulture);
        public static string BackToDashboard => ResourceManager.GetString("BackToDashboard", resourceCulture);
        public static string NoStations => ResourceManager.GetString("NoStations", resourceCulture);
        public static string Connectors => ResourceManager.GetString("Connectors", resourceCulture);
        public static string MaintenanceIssues => ResourceManager.GetString("MaintenanceIssues", resourceCulture);
        public static string DetailsAction => ResourceManager.GetString("DetailsAction", resourceCulture);
        public static string CreateAction => ResourceManager.GetString("CreateAction", resourceCulture);
        public static string EditAction => ResourceManager.GetString("EditAction", resourceCulture);
        public static string DeleteAction => ResourceManager.GetString("DeleteAction", resourceCulture);
        public static string SetAvailableAction => ResourceManager.GetString("SetAvailableAction", resourceCulture);
        public static string SetInUseAction => ResourceManager.GetString("SetInUseAction", resourceCulture);
        public static string SetMaintenanceAction => ResourceManager.GetString("SetMaintenanceAction", resourceCulture);
        public static string PriceLabel => ResourceManager.GetString("PriceLabel", resourceCulture);
        public static string MaxPowerLabel => ResourceManager.GetString("MaxPowerLabel", resourceCulture);
    }
}
