// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace App.Resources.Views.Company.Dashboard {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        internal Index() {
        }

        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    var temp = new System.Resources.ResourceManager("WebAppClient.App.Resources.Views.Company.Dashboard.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        public static System.Globalization.CultureInfo Culture {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string Title => ResourceManager.GetString("Title", resourceCulture);
        public static string Heading => ResourceManager.GetString("Heading", resourceCulture);
        public static string FromUtc => ResourceManager.GetString("FromUtc", resourceCulture);
        public static string ToUtc => ResourceManager.GetString("ToUtc", resourceCulture);
        public static string ApplyFilters => ResourceManager.GetString("ApplyFilters", resourceCulture);
        public static string StationStatusAction => ResourceManager.GetString("StationStatusAction", resourceCulture);
        public static string MaintenanceQueueAction => ResourceManager.GetString("MaintenanceQueueAction", resourceCulture);
        public static string TotalStations => ResourceManager.GetString("TotalStations", resourceCulture);
        public static string TotalStationsHint => ResourceManager.GetString("TotalStationsHint", resourceCulture);
        public static string TotalReservations => ResourceManager.GetString("TotalReservations", resourceCulture);
        public static string TotalReservationsHint => ResourceManager.GetString("TotalReservationsHint", resourceCulture);
        public static string AvgUtilization => ResourceManager.GetString("AvgUtilization", resourceCulture);
        public static string PeakHoursLabel => ResourceManager.GetString("PeakHoursLabel", resourceCulture);
        public static string Revenue => ResourceManager.GetString("Revenue", resourceCulture);
        public static string AvgSessionDurationLabel => ResourceManager.GetString("AvgSessionDurationLabel", resourceCulture);
        public static string StationPerformanceHeading => ResourceManager.GetString("StationPerformanceHeading", resourceCulture);
        public static string NoStationData => ResourceManager.GetString("NoStationData", resourceCulture);
        public static string StationColumn => ResourceManager.GetString("StationColumn", resourceCulture);
        public static string HealthColumn => ResourceManager.GetString("HealthColumn", resourceCulture);
        public static string UtilizationColumn => ResourceManager.GetString("UtilizationColumn", resourceCulture);
        public static string ActionsColumn => ResourceManager.GetString("ActionsColumn", resourceCulture);
        public static string DetailsAction => ResourceManager.GetString("DetailsAction", resourceCulture);
        public static string MaintenanceHeading => ResourceManager.GetString("MaintenanceHeading", resourceCulture);
        public static string NoMaintenanceData => ResourceManager.GetString("NoMaintenanceData", resourceCulture);
        public static string UtilizationTrend => ResourceManager.GetString("UtilizationTrend", resourceCulture);
        public static string RevenueTrend => ResourceManager.GetString("RevenueTrend", resourceCulture);
        public static string TrendAverage => ResourceManager.GetString("TrendAverage", resourceCulture);
        public static string TrendPeak => ResourceManager.GetString("TrendPeak", resourceCulture);
        public static string TrendLowest => ResourceManager.GetString("TrendLowest", resourceCulture);
    }
}
