//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Views.Root.Station {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Details {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Details() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("App.Resources.Views.Root.Station.Details", typeof(Details).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        public static string StatusAvailable {
            get {
                return ResourceManager.GetString("StatusAvailable", resourceCulture);
            }
        }
        
        public static string StatusInUse {
            get {
                return ResourceManager.GetString("StatusInUse", resourceCulture);
            }
        }
        
        public static string StatusMaintenance {
            get {
                return ResourceManager.GetString("StatusMaintenance", resourceCulture);
            }
        }
        
        public static string PricePerKwh {
            get {
                return ResourceManager.GetString("PricePerKwh", resourceCulture);
            }
        }
        
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        public static string MaxPower {
            get {
                return ResourceManager.GetString("MaxPower", resourceCulture);
            }
        }
        
        public static string BackToStations {
            get {
                return ResourceManager.GetString("BackToStations", resourceCulture);
            }
        }
        
        public static string Connectors {
            get {
                return ResourceManager.GetString("Connectors", resourceCulture);
            }
        }
        
        public static string NoConnectors {
            get {
                return ResourceManager.GetString("NoConnectors", resourceCulture);
            }
        }
        
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        public static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        public static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        public static string EstimatedEnergy {
            get {
                return ResourceManager.GetString("EstimatedEnergy", resourceCulture);
            }
        }
        
        public static string ReserveNow {
            get {
                return ResourceManager.GetString("ReserveNow", resourceCulture);
            }
        }
        
        public static string MyReservations {
            get {
                return ResourceManager.GetString("MyReservations", resourceCulture);
            }
        }
        
        public static string NoAvailability {
            get {
                return ResourceManager.GetString("NoAvailability", resourceCulture);
            }
        }
        
        public static string ExistingReservations {
            get {
                return ResourceManager.GetString("ExistingReservations", resourceCulture);
            }
        }
        
        public static string NoStationReservations {
            get {
                return ResourceManager.GetString("NoStationReservations", resourceCulture);
            }
        }
        
        public static string CalculatorTitle {
            get {
                return ResourceManager.GetString("CalculatorTitle", resourceCulture);
            }
        }
        
        public static string SelectVehicle {
            get {
                return ResourceManager.GetString("SelectVehicle", resourceCulture);
            }
        }
        
        public static string NoVehicles {
            get {
                return ResourceManager.GetString("NoVehicles", resourceCulture);
            }
        }
        
        public static string BatteryLevelTitle {
            get {
                return ResourceManager.GetString("BatteryLevelTitle", resourceCulture);
            }
        }
        
        public static string CurrentBattery {
            get {
                return ResourceManager.GetString("CurrentBattery", resourceCulture);
            }
        }
        
        public static string DesiredBattery {
            get {
                return ResourceManager.GetString("DesiredBattery", resourceCulture);
            }
        }
        
        public static string EnergyLabel {
            get {
                return ResourceManager.GetString("EnergyLabel", resourceCulture);
            }
        }
        
        public static string DurationLabel {
            get {
                return ResourceManager.GetString("DurationLabel", resourceCulture);
            }
        }
        
        public static string CostLabel {
            get {
                return ResourceManager.GetString("CostLabel", resourceCulture);
            }
        }
        
        public static string MinuteShort {
            get {
                return ResourceManager.GetString("MinuteShort", resourceCulture);
            }
        }
        
        public static string CurrencyCode {
            get {
                return ResourceManager.GetString("CurrencyCode", resourceCulture);
            }
        }
        
        public static string StatusActive {
            get {
                return ResourceManager.GetString("StatusActive", resourceCulture);
            }
        }
        
        public static string StatusStarted {
            get {
                return ResourceManager.GetString("StatusStarted", resourceCulture);
            }
        }
    }
}
