// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace App.Resources.Views.Admin.Dashboard {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        internal Index() {
        }

        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    var temp = new System.Resources.ResourceManager("App.Resources.Views.Admin.Dashboard.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        public static System.Globalization.CultureInfo Culture {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string Title => ResourceManager.GetString("Title", resourceCulture);
        public static string Heading => ResourceManager.GetString("Heading", resourceCulture);
        public static string ReservationsInPeriod => ResourceManager.GetString("ReservationsInPeriod", resourceCulture);
        public static string PeriodHint => ResourceManager.GetString("PeriodHint", resourceCulture);
        public static string TotalCompanies => ResourceManager.GetString("TotalCompanies", resourceCulture);
        public static string CompaniesHint => ResourceManager.GetString("CompaniesHint", resourceCulture);
        public static string TotalCompanyUsers => ResourceManager.GetString("TotalCompanyUsers", resourceCulture);
        public static string CompanyUsersHint => ResourceManager.GetString("CompanyUsersHint", resourceCulture);
        public static string TotalClientUsers => ResourceManager.GetString("TotalClientUsers", resourceCulture);
        public static string ClientUsersHint => ResourceManager.GetString("ClientUsersHint", resourceCulture);
        public static string FromUtc => ResourceManager.GetString("FromUtc", resourceCulture);
        public static string ToUtc => ResourceManager.GetString("ToUtc", resourceCulture);
        public static string ApplyFilters => ResourceManager.GetString("ApplyFilters", resourceCulture);
        public static string ManageCompaniesAction => ResourceManager.GetString("ManageCompaniesAction", resourceCulture);
        public static string ViewAuditAction => ResourceManager.GetString("ViewAuditAction", resourceCulture);
    }
}
